environment:
  matrix:
    - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run vscode:prepublish
test_script:
  - node --version
  - npm --version
  - tslint --project .
  - npm test --silent
build: off